lolchampcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('lolchamps/', views.lolchamps_index, name='lolchamps'),
    path('about/', views.about, name='about'),
    path('lolchamps/<int:lolchamp_id>/', views.lolchamp_details, name='details'),
    path('lolchamps/create/', views.LolChampCreate.as_view(), name='lolchamps_create'),
    path('lolchamps/<int:pk>/update/', views.LolChampUpdate.as_view(), name='lolchamps_update'),
    path('lolchamps/<int:pk>/delete/', views.LolChampDelete.as_view(), name='lolchamps_delete'),
    path('lolchamps/<int:lolchamp_id>/add_ability/', views.add_ability, name='add_ability'),
    path('lolchamps/<int:lolchamp_id>/assoc_item/<int:item_id>/', views.assoc_item, name='assoc_item'),
    path('items/', views.ItemList.as_view(), name='items_index'),
    path('items/<int:pk>/', views.ItemDetail.as_view(), name='items_detail'),
    path('items/create/', views.ItemCreate.as_view(), name='items_create'),
    path('items/<int:pk>/update/', views.ItemUpdate.as_view(), name='items_update'),
    path('items/<int:pk>/delete/', views.ItemDelete.as_view(), name='items_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

class Item(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    cost = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('items_detail', kwargs={'pk': self.id})

class LolChamp(models.Model):
    name = models.CharField(max_length=100)
    role = models.CharField(max_length=100)
    difficulty = models.CharField(max_length=100)
    items = models.ManyToManyField(Item)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('details', kwargs={'lolchamp_id': self.id})
    
class Ability(models.Model):
    name = models.CharField('ability name', max_length=100)
    description = models.CharField(max_length=500)

    lolchamp = models.ForeignKey(LolChamp, on_delete=models.CASCADE)

    def __str__(self):
        return f'Ability: {self.name} -- Description: {self.description}'
    

                      

main_app/forms.py
from django.forms import ModelForm
from .models import Ability

class AbilityForm(ModelForm):
  class Meta:
    model = Ability
    fields = ['name', 'description']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import LolChamp, Item
from .forms import AbilityForm

def home(request):
    return render(request, 'home.html')

def lolchamps_index(request):
    lolchamps = LolChamp.objects.all()
    return render(request, 'lolchamps/index.html', {
        'lolchamps': lolchamps
    })

def about(request):
    return render(request, 'about.html')

def lolchamp_details(request, lolchamp_id):
    lolchamp = LolChamp.objects.get(id=lolchamp_id)
    id_list = lolchamp.items.all().values_list('id')
    items_lolchamp_doesnt_have = Item.objects.exclude(id__in=id_list)
    ability_form = AbilityForm()
    return render(request, 'lolchamps/details.html', {
        'lolchamp': lolchamp,
        'ability_form': ability_form,
        'items': items_lolchamp_doesnt_have
        })

def assoc_item(request, lolchamp_id, item_id):
   LolChamp.objects.get(id=lolchamp_id).items.add(item_id)
   return redirect ('details', lolchamp_id=lolchamp_id)

class LolChampCreate(CreateView):
    model = LolChamp
    fields = ['name', 'role', 'difficulty']
    success_url = '/lolchamps/{id}'

class LolChampUpdate(UpdateView):
    model = LolChamp
    fields = ['name', 'role', 'difficulty']

class LolChampDelete(DeleteView):
    model = LolChamp
    success_url = '/lolchamps'

def add_ability(request, lolchamp_id):
    form = AbilityForm(request.POST)
    if form.is_valid():
        new_ability = form.save(commit=False)
        new_ability.lolchamp_id = lolchamp_id
        new_ability.save()
    return redirect('details', lolchamp_id=lolchamp_id)

class ItemList(ListView):
  model = Item

class ItemDetail(DetailView):
  model = Item

class ItemCreate(CreateView):
  model = Item
  fields = '__all__'

class ItemUpdate(UpdateView):
  model = Item
  fields = ['name', 'description', 'cost']

class ItemDelete(DeleteView):
  model = Item
  success_url = '/items'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>LoL Champ Collector</h1>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>LoL Champ Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;LoL Champ Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="/about">About</a></li>
          <li><a href="{% url 'lolchamps_create' %}">Add a LoL Champ</a></li>
          <li><a href="/lolchamps">View All My LoL Champs</a></li>
          <li><a href="{% url 'items_create' %}">Add Item</a></li>
          <li><a href="{% url 'items_index' %}">View All Items</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 LoL Champ Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Welcome to LoL Champ Collector!</h1>

{% endblock %}

main_app/templates/lolchamps/details.html
{% extends 'base.html' %}
{% block content %}

<h1>LoL Champion Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ lolchamp.name }}</span>
        <p>Role: {{ lolchamp.role }}</p>
        <p>Difficulty: {{ lolchamp.difficulty|linebreaks }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'lolchamps_update' lolchamp.id %}">Edit</a>
        <a href="{% url 'lolchamps_delete' lolchamp.id %}">Delete</a>
      </div>
    </div>
  </div>
  <!-- New Markup Below -->
  <div class="col s6">
    <form action="{% url 'add_ability' lolchamp.id %}" method="POST">
      {% csrf_token %}
      {{ ability_form.as_p }}
      <input type="submit" class="btn" value="Add Ability">
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Ability</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {% for ability in lolchamp.ability_set.all %}
        <tr>
          <td>{{ability.name}}</td>
          <td>{{ability.description}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- New Markup Above -->
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ lolchamp.name }}'s Items</h3>
    {% if lolchamp.items.count %}
    {% for item in lolchamp.items.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A {{ item.name }}
        </span>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>No Items</h5>
    {% endif %}
  </div>
  <!-- Available items will come after this line -->
  <!-- New Markup Below -->
  <div class="col s6">
    <h3>Available Items</h3>
    {% if items.count %}
    {% for item in items.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A {{ item.name }}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_item' lolchamp.id item.id%}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>{{lolchamp.name}} Already Has All Items Available</h5>
    {% endif %}
  </div>
</div>
{% endblock %}

main_app/templates/lolchamps/index.html
{% extends 'base.html' %}
{% block content %}

{% for lolchamp in lolchamps %}
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ lolchamp.name }}</span>
      <p>Role: {{ lolchamp.role }}</p>
      <p>Difficulty: {{ lolchamp.difficulty }}</p>
    </div>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/item_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Item</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'items_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/item_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Item Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ item.name }}</span>
        <p>Name: {{ item.name }}</p>
        <p>Description: {{ item.description }}</p>
        <p>Cost: {{ item.cost }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'items_update' item.id %}">Edit</a>
        <a href="{% url 'items_delete' item.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/item_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Item</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/item_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Item List</h1>

{% for item in item_list %}
  <a href="{% url 'items_detail' item.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ item.name }}</span>
            <p>Name: {{ item.name }}</p>
            <p>Description: {{ item.description }}</p>
            <p>Cost: {{ item.cost }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/lolchamp_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete LoL Champion</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'details' lolchamp.id %}">Cancel</a>
  </form>
 
{% endblock %}

main_app/templates/main_app/lolchamp_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add LoL Champion</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
        <!-- Render the inputs inside of <tr>s & <td>s -->
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}